# Generated by Django 4.1.2 on 2022-11-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('F', 'FAILED'), ('S', 'SUCCESS')], default='P', max_length=1, null=True),
        ),
    ]
