# Generated by Django 4.1.2 on 2022-11-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cartitems_product_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartitems'),
        ),
    ]
